### ISSUE TITLE
Missing Docker architecture

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [alexeyantropov/clickhouse_table_exporter#6]
Hey,

I was trying to use this exporter but it is missing the `linux/amd64` architecture.

Thanks,
MiguelNdeCarvalho

**Comment by alexeyantropov** [comment]
> Hey,
> 
> I was trying to use this exporter but it is missing the `linux/amd64` architecture.
> 
> Thanks, MiguelNdeCarvalho

I will check it after my vacation. Give me three weeks for. But you always can build the Dockerfile if you want. There is the Dockerfile https://github.com/alexeyantropov/clickhouse_table_exporter/blob/main/Dockerfile .

**Comment by MiguelNdeCarvalho** [comment]
Thanks @alexeyantropov I will wait for that, in the meantime I will use my own build, but let's add support for amd64 officially

**Comment by alexeyantropov** [comment]
> Thanks @alexeyantropov I will wait for that, in the meantime I will use my own build, but let's add support for amd64 officially

Uhhh, I've finally done it. In the [20240620](https://github.com/alexeyantropov/clickhouse_table_exporter/releases/tag/20240620) release I changed the the platform on linux/amd64 and the versioned and the latest docker images are okay now.

**Comment by MiguelNdeCarvalho** [comment]
Thank you @alexeyantropov!
